version: '3.8'

services:
  api:
    build: .
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_DSN=host=db user=postgres password=postgres dbname=consultor port=5432 sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consultor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
